### ISSUE TITLE
Where do i get firmware binaries?

### ISSUE THREAD

**Issue by goshante** [OK2MOP/MD1702-tools#6] opened 2022-04-10 19:01 UTC
Is this a secret or what? There is literaly NO SIGNLE PLACE IN INTERNET with firmware for DM-1702!!!!!!!! Is this a some sort of conspiracy or what?
WHERE CAN I DOWNLOAD IT? WHY NOT IN REPOSITORY???
I need BIN FILES

**Comment by OK2MOP** [comment] 2022-04-12 14:26
Look, the binaries are linked in a discussion thread elsewhere, actually this repo is linked from there as well. Look for DM-X not DM-1702 (the discussion is in top links) . The problem is:
- there are multiple firmware files and some make some radios dead (e.g. old versions on L05 radios and vice versa). 
- official firmware files are encrypted and you cannot use this tool with them.
- unofficially extracted firmware files require this tool to be flashed or very old CPS.
- sharing the firmware is gray area and even I do not have newer versions because nobody shared them with me.

So I am intentionally not including them

Lastly it has nothing to do with this repo so I am closing the request. If you have contacted me by E-mail instead, I would have provided a link, but on your own risk you will brick the radio (and unless you have a backup of present firmware, you would not be able to go back).

**Closed as completed by OK2MOP** 2022-04-12 14:26 UTC
